### ISSUE TITLE
destination folder - Linux installation procedures (documentation) 

### ISSUE THREAD

**Issue by mayeulk** [dalibo/emaj#10]
`cp emaj.control $(pg_config --sharedir)/extension/.`
The above does not always work, it might produce this message:

> You need to install postgresql-server-dev-X.Y for building a server-side extension or libpq-dev for building a client-side application. 

This is the result of using pg_config.
There are several issues with the (nice) following command: `$(pg_config --sharedir)`
1) There are sometimes several versions of pg_config (the one used might not be the one the user wants -- in case of several versions of PG installed in parallels).
2) It answers an error message when postgresql-server-dev-X.Y is not installed (but the extension works fine without this package).

I suggest a few words of text instead. For instance:

### (proposed patch)

As a super-user, copy the files to the extension folder of the postgresql version you want to use. In some cases, `pg_config --sharedir` will tell you the folder name. If this is appropriate, you can use the following commands (as a super-user, or pre-pended with `sudo`):

```
cp emaj.control $(pg_config --sharedir)/extension/.
cp sql/emaj* $(pg_config --sharedir)/extension/.
```

If this is not appropriate, you have to specify explicitly the destination:

For instance, on Debian 9 (stretch) with PostgreSQL 10:
```
cp emaj.control /usr/share/postgresql/10/extension/.
cp sql/emaj* /usr/share/postgresql/10/extension/.
```

**Comment by beaud76** [comment]
Thank You very much for your proposal.
We very recently changed the installation procedure on Linux avoiding to use the pgxn client that needs the postgres -devel packages, and so went back to more trivial cp commands rather than a "make install". And the new procedure also brings some similar constraints...
I will apply your proposal in the documentation.
Thanks again

**Comment by beaud76** [comment]
I have integrated the proposal, with some adjustments.
Commit 7399fc5.
mayeulk, can you check the changes ?

**Comment by mayeulk** [comment]
Hi,

I have not executed the commands but the changes look fine, thanks;  except maybe for line 41:


The latest E-Maj version is now installed and referenced by PostgreSQL. The e-maj-<version> directory contains the file tree :doc:`described here <content>`.


This line displays verbatim in github, meaning that  there are two columns, 2 apostrophs and a `<content>` tag  visible in
:doc:`described here <content>`     (but maybe this disappears in html?).

Cheers,

Mayeul

**Comment by beaud76** [comment]
Yes, this seems to be an effect of the github display of rst files. In the online documentation site, this looks good. (http://emaj.readthedocs.io/en/latest/install.html)
Thanks. 
Philippe.
