### ISSUE TITLE
Improve the pg_dump regression test

### ISSUE THREAD

**Issue by beaud76** [dalibo/emaj#15]
The test that uses pg_dump to dump an E-Maj environment and restore it in another cluster (in another postgres version) doesn't produce stable enough results. As a result, it is useless. Rethink it, starting with a proper E-Maj install + some tables group manipulation, then a save, then a restore and some final groups use.

**Comment by tilkow** [comment]
Hi Philippe,
  I will work on it.
Best regards

**Comment by beaud76** [comment]
Thanks by advance

**Comment by tilkow** [comment]
Adding controls to finalize the test (via #24)

**Comment by beaud76** [comment]
Your proposal has been included into the commit 3ee564bb6f08b610d71b33b240b108095a0e3ad3, with some minor improvements.
Some minor changes in your plpgsql code, some changes also in the after_restore.sql script to get stable results, and some adjustment of the documentation.
I have also added a test in the regress.sh menu, dumping in pg 9.5 and restoring in pg 11.
Thank You very much for you PR.
