### ISSUE TITLE
Rewrite clients in python or perl

### ISSUE THREAD

**Issue by beaud76** [dalibo/emaj#18]
Both old emajParallelRollback and emajRollbackMonitor clients are written in php.
Generally, php is not installed on server by default, while perl and python are already here on most linux platforms hosting postgres instances. As both langages have the capability to access a postgres database with several connection in parallel, it may be a better choice.

**Comment by tilkow** [comment]
Perl scripts are submit via #21

**Comment by beaud76** [comment]
Thank You very much. 
Patch applied.
