### ISSUE TITLE
Probleme de migration de Postgresql 9.6 en 10 avec changement de version de emaj

### ISSUE THREAD

**Issue by quidoz** [dalibo/emaj#27]
Bonjour

J'ai fait une petite base de test avant les vacances sur un serveur postgresql9.6 (version emaj ?). De retour de vacances, j'ai migré cela sur un serveur postgresql 10 avec emaj 2.3.1. Je travaille sur debian 9.5. J'ai fait la migration à l'aide de la commande pg_dump -U postgres -f test_emaj.dump test_emaj et j'ai régénéré avec psql -f .  Problème je ne retrouve pas mes petits (groupe, marque,  ...) et donc je ne peux pas jouer pour retrouver des anciennes valeurs.. (NDR ; il y a des erreurs à la régénération)
Comment aurais je du faire pour conserver le tout 

A+
MCQ

**Comment by beaud76** [comment]
Bonjour,

Le souci vient du fait qu'on ne peut pas sauvegarder un environnement E-Maj dans une version par pg_dump et le restaurer dans une autre. En effet, entre 2 versions, la structure des tables internes peut changer. Dès lors, il y a toutes les chances pour que la tentative de rechargement du contenu produise une erreur.

Si on veut transporter la base d'une instance PostgreSQL à une autre, que la version de postgres soit la même ou non, il faut donc avoir la même version d'E-Maj de chaque côté. Dans ton cas de figure, le changement de version d'E-Maj peut se faire soit avant soit après le changement d'instance (par une simple commande "ALTER EXTENSION UPDATE TO <version>". Le script sous-jacant fait les ajustements de structure nécessaires.

Le chapitre de la documentation qui traite des changements de version PostgreSQL n'est pas assez précis sur ce sujet. Je vais le compléter.

Concernant la version d'E-Maj initialement installée, tu devrais pouvoir la retrouver en regardant dans ton fichier dump test_emaj.dump. Dans le contenu de la table emaj_param, tu dois retrouver une ligne (probablement la seule de la table dans ton cas) avec une clé 'emaj_version' et ... la version. Si tu as encore accès à l'ancienne base, un simple "SELECT * FROM emaj.emaj_param;" donnera aussi la réponse.

Cdlt. Philippe.

**Comment by beaud76** [comment]
La documentation est maintenant plus explicite. ([https://emaj.readthedocs.io/fr/latest/postgresUpgrade.html])
