### ISSUE TITLE
Use of remove_table function not delete on emaj_group_def

### ISSUE THREAD

**Issue by dhaddadi** [dalibo/emaj#39]
Hello I have a little issue with version 3.2.0

First I upgrade from 3.0.0 to 3.2.0 how ? 
Just on download the new version locally and 
I performed these commands 

=> cp emaj.control /usr/pgsql-10/share/extension/.
=> cp sql/emaj--* /usr/pgsql-10/share/extension/.
with postgreql user on database 
=> ALTER EXTENSION emaj UPDATE;

But now I want to use these functions 
SELECT emaj.emaj_remove_table('newton', 'dhi_test_1');
SELECT emaj.emaj_assign_table('newton', 'dhi_test_1', 'newton_datalake');
on a existing group 
but I see nothing on table  emaj.emaj_group_def (seems not be updated after use of these functions)

![bug_version_1](https://user-images.githubusercontent.com/29089843/75460604-f25c2600-5981-11ea-95fb-06b9fd89cc2b.PNG)

**Comment by beaud76** [comment]
Hi Djamel,

"ALTER EXTENSION emaj UPDATE;" is the right command to upgrade the extension.

Regarding the emaj_group_def content, this table is effectively not updated by the dynamic emaj_assign_... and emaj_remove_... functions.
And these functions do not use emaj_group_def at all.

In fact there are 2 ways to handle tables groups structure.
- The old one uses the emaj_group_def table. The emaj administrator processes in 2 steps : 1) prepare the configuration by filling emaj_group_def and then 2) create or alter the groups with the emaj_create_group() or emaj_alter_group() functions.
- The new one directly applies the configuration changes without passing through the emaj_group_def table, by using these recently introduced emaj_assign_... and emaj_remove_... functions (and some others).

These two technics are not supposed to be mixed. However, it is possible to setup the emaj_group_def table's content from the existing groups state with the emaj_sync_def_group() function.

You may find some more explanations in the documentation (here in French, but also available in English) :
[(https://emaj.readthedocs.io/fr/v3.2.0/groupsCreationFunctions.html)]
or [https://emaj.readthedocs.io/fr/v3.2.0/alterGroups.html]

If you want to discover a little bit more what is inside the engine, you can have a look at the emaj_relation table content. You will find the application tables and sequences of you tables groups ;-)

Best regards. Philippe.

**Comment by dhaddadi** [comment]
Hello 
Yes I understand, you explanation solve my issue !
Great 

Best regards
Djamel
