### ISSUE TITLE
PostgreSQL 15 support

### ISSUE THREAD

**Issue by devrimgunduz** [dalibo/emaj#46]
Hi,

I see that v15 support is committed. Can you please release a new version which includes that patch? v15 is due in 2 weeks.

Thanks!

Regards, Devrim

**Comment by beaud76** [comment]
Hi Devrim,
This is done, with the new 4.1.0 version.
Best regards. Philippe.

**Comment by devrimgunduz** [comment]
Thanks  a lot!
