### ISSUE TITLE
Emaj_web fails: fields missing in Emaj tables and functions 

### ISSUE THREAD

**Issue by mayeulk** [dalibo/emaj#49]
Maybe I failed to get the install working with two compatible versions of emaj_web and emaj (=> clarify documentation).
Or, there might be some mismatch between emaj structure and emaj_web requirements (=> patch this).

I *seems* to me that, looking at the code, some of these fields _might_ exists in some versions. Because I'm unsure, I group these issues into one github issue.

Seen on PostgreSQL version: 15.3. PostgreSQL and LAMP in two Docker containers. Scripted install.
E-Maj button in Emaj_web says: E-Maj environment consistency: Dignostics: 	No error detected

On fresh install (downloaded today) of emaj and emaj_web, I have several issues with emaj_web.
emaj.emaj_param says: emaj_version is '<devel>' (without the quotes). param_value_numeric, param_value_boolean, param_value_interval are null.

Trying to upgrade emaj extension to devel fails:
`ALTER EXTENSION emaj UPDATE;`
NOTICE:  version "devel" of extension "emaj" is already installed

Below are the issues, separated by lines.

Issue 1
---------------------------------------------------------
Roolback (with comment) and a few other things do not work with emaj_web

In emaj_web, making a logged rollback with a comment raises a "function does not exist" error:
SQL error:
ERROR:  function emaj.emaj_logged_rollback_group(unknown, unknown, boolean, unknown) does not exist
LINE 1: SELECT * FROM emaj.emaj_logged_rollback_group('group_exo','R...
                      ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
In statement:
`SELECT * FROM emaj.emaj_logged_rollback_group('group_exo','RLBK_RLBK_mark3_10.25.40.2022_DONE_10.28.54.4201_START',true,'comment logged rollback')
`

-- Same when launching this SQL command in pgadmin:
`SELECT * FROM emaj.emaj_rollback_group('group_exo', 'EMAJ_LAST_MARK', false, 'test rollback');
`
ERROR:  function emaj.emaj_rollback_group(unknown, unknown, boolean, unknown) does not exist
LINE 1: SELECT * FROM emaj.emaj_rollback_group('group_exo', 'EMAJ_LA...
                      ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
-- Hint is not useful here. the comment input parameter is not implemented in the version I have for emaj.emaj_rollback_group
-- this works

but this works:
```
SELECT * FROM emaj.emaj_rollback_group('group_exo', 'EMAJ_LAST_MARK', false);
-- rlbk_message: 0 / 4 tables effectively processed.  

```
I think, same issue with logged rollback (if comments are wanted)

Issue 2
-------------------------------------------------------

Clicking the E-maj Rollbacks red icon on emaj_web

```
SQL error:
ERROR:  column "rlbk_start_datetime" does not exist
LINE 2:       to_char(rlbk_start_datetime,'YYYY/MM/DD HH24:MI:SS.US ...
                      ^
In statement:
SELECT rlbk_id, array_to_string(rlbk_groups,', ') as rlbk_groups_list, rlbk_status,
						to_char(rlbk_start_datetime,'YYYY/MM/DD HH24:MI:SS.US OF') AS rlbk_start_datetime,
						to_char(rlbk_end_datetime,'YYYY/MM/DD HH24:MI:SS.US OF') AS rlbk_end_datetime,
						to_char(rlbk_end_datetime - rlbk_start_datetime, 'DD HH24:MI:SS.US') as rlbk_duration,
						rlbk_mark, rlbk_is_logged, rlbk_nb_session, rlbk_comment
					FROM emaj.emaj_rlbk
					WHERE rlbk_status IN ('COMPLETED','COMMITTED','ABORTED')
					ORDER BY rlbk_id DESC
					LIMIT 1000
```

When trying to perform a rollback with emaj_web:

E-Maj: Rollback a tables group
Rollback execution report for the tables groups "group_exo" to the mark "del c"
```
SQL error:
ERROR:  function emaj.emaj_logged_rollback_group(unknown, unknown, boolean, unknown) does not exist
LINE 1: SELECT * FROM emaj.emaj_logged_rollback_group('group_exo','d...
                     ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
In statement:
SELECT * FROM emaj.emaj_logged_rollback_group('group_exo','del c',true,'undo del c')
```

Issue 3
----------------------
On emaj_web, clicking Rollbacks E-Maj (red arrow) on the left also gives:

```
Erreur SQL :

ERROR:  column "rlbk_comment" does not exist
-- LINE 5:       rlbk_mark, rlbk_is_logged, rlbk_nb_session, rlbk_comme...
                                                          ^

-- Dans l'instruction :

SELECT rlbk_id, array_to_string(rlbk_groups,', ') as rlbk_groups_list, rlbk_status,
						to_char(rlbk_start_datetime,'YYYY/MM/DD HH24:MI:SS.US OF') AS rlbk_start_datetime,
						to_char(rlbk_end_datetime,'YYYY/MM/DD HH24:MI:SS.US OF') AS rlbk_end_datetime,
						to_char(rlbk_end_datetime - rlbk_start_datetime, 'DD HH24:MI:SS.US') as rlbk_duration,
						rlbk_mark, rlbk_is_logged, rlbk_nb_session, rlbk_comment
					FROM emaj.emaj_rlbk
					WHERE rlbk_status IN ('COMPLETED','COMMITTED','ABORTED')
					ORDER BY rlbk_id DESC
					LIMIT 1000
```

-- I fixed part of the above with this:
```

ALTER TABLE emaj.emaj_rlbk
ADD COLUMN IF NOT EXISTS rlbk_start_datetime timestamp with time zone,
ADD COLUMN IF NOT EXISTS rlbk_comment varchar;
```

Adding COLUMN rlbk_start_datetime helps to display the "Completed E-Maj rollbacks" table 
-- I'll be happy to work on a patch here, if it helps.

Issue 4
-------------------------------------------------------
--  But even after this hot-fix, Emaj_web's "Rollback start" is still empty.
-- and "Consolidable E-Maj logged rollbacks" table fails (the field is needed in the function too) with:
```
SQL error:

ERROR:  column "rlbk_comment" does not exist
LINE 7:      rlbk_completion_pct, rlbk_comment FROM emaj.emaj_rollba...
                                  ^

In statement:

SELECT rlbk_id, array_to_string(rlbk_groups,', ') AS rlbk_groups_list, rlbk_mark,
					to_char(rlbk_mark_datetime,'YYYY/MM/DD HH24:MI:SS.US OF') AS rlbk_mark_datetime,
					rlbk_is_logged,	rlbk_nb_session, rlbk_nb_table, rlbk_nb_sequence, rlbk_eff_nb_table, rlbk_status,
					to_char(rlbk_start_datetime,'YYYY/MM/DD HH24:MI:SS.US OF') AS rlbk_start_datetime,
					to_char(rlbk_elapse,'DD HH24:MI:SS.US') AS rlbk_current_elapse,
					to_char(rlbk_remaining, 'DD HH24:MI:SS.US') AS rlbk_remaining,
					rlbk_completion_pct, rlbk_comment FROM emaj.emaj_rollback_activity()
				ORDER BY rlbk_id DESC
```
Thank you.

**Comment by beaud76** [comment]
Hi mayeulk,
Nice to get some news from you ;-).
It looks like you have a mismatch between emaj and emaj_web versions.
As indicating in the documentation, the standart way to install both versions is:
- get a stable emaj version from pgxn.org (4.2.0 for instance),
- get emaj_web from github.

This may look ugly, but it allows to handle cases when there are several databases with different emaj extension versions (within the supported cross-versions matrix).
A devel emaj extension can be installed from github also. But in this case, 1) emaj_web must be installed at the same time (they are normally synchronized), 2) there is no way to handle upgrades safely, and 3) it blocks any attempt to have several databases with different devel emaj versions. Finally, this is intended for development purposes only.
In your case, after having downloaded a fresh emaj version from github, the ALTER EXTENSION UPDATE attempt failed because for the extension manager, the installed and the new versions are the same. However, it should work if you DROP the extension and reCREATE it.
I will add an issue in the emaj_web repo to report a warning in the E-Maj button when the extension version is devel.
Thanks again for the detailed report.
Philippe.

**Comment by mayeulk** [comment]
Hi Philippe, thanks a lot for the detailed explanation, and for this nice product ;- )
Problem solved.

I was confused, as the v4.2.0 on github is quite different from the version with same number on pgxn, see below:
(both folders come from the 2 wget as seen in my first Dockerfile below)


github on the left  _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ pgxn on the right
![image](https://github.com/dalibo/emaj/assets/768570/235b44e9-3e63-4a32-bdf6-b405ad6c76f8)

(a nice 1st-April joke :D ).
Unless I'm mistaken, installing the github version flagged '4.2.0' (in the sense of github flag) makes it have a 'devel' flag (in the sense of pg extension flag).

I had not seen the "Download" button at pgxn, and the words "pgxn client" made me (wrongly) think that there was no wget-way to get the zip file.

I've just made a PR on the French doc (master/docs/fr/install.rst), for your review; to help future users. If you find it right, I'll add it to the English page too.

Another option (which may help in debugging Emaj/Emaj_web cases like mine in this issue) is a docker-compose.yml plus  Dockerfiles. In case it helps some one:

Below my pg Dockerfile (updated for pgxn)
```
FROM postgres:15.3-alpine3.18

ENV emajversion=4.2.0

# RUN wget https://github.com/dalibo/emaj/archive/refs/tags/v${emajversion}.zip
RUN wget https://api.pgxn.org/dist/e-maj/${emajversion}/e-maj-${emajversion}.zip

RUN unzip e-maj-${emajversion}.zip

# Location of the SHAREDIR directory is: pg_config --sharedir
ENV pgsharedir=/usr/local/share/postgresql

RUN cp e-maj-${emajversion}/emaj.control $pgsharedir/extension/.

RUN cp e-maj-${emajversion}/sql/emaj--* $pgsharedir/extension/.

# Copy SQL files containing instructions to build and populate postgres database
# One of these SQL files contains:'CREATE EXTENSION emaj CASCADE;'
COPY *.sql /docker-entrypoint-initdb.d/

# Allow container to listen on port 5432
EXPOSE 5432
```
emaj_web Dockerfile:
```
ARG PHP_VERSION=8.2
FROM php:${PHP_VERSION}-apache

# If using docker-compose.yml, put the name of the container hosting the database (here: root_db)
ENV db_host=root_db

# Use this with great caution, 'true' is prefered
ENV extra_login_security=false

ENV defaultdb=postgres

RUN apt-get update -qq && \
    apt-get install -qy \
    unzip \
    postgresql-client \
    wget \
    nano

# TODO: remove nano when container fixed

# Install PHP postgres and intl extensions
RUN apt-get install -qy \
    libpq-dev \
    && docker-php-ext-configure pgsql -with-pgsql=/usr/local/pgsql \
    && docker-php-ext-install pgsql

RUN apt-get install -qy \
    libicu-dev \
    && docker-php-ext-configure intl \
    && docker-php-ext-install intl

# RUN mv "$PHP_INI_DIR/php.ini-development" "$PHP_INI_DIR/php.ini"
RUN mv "$PHP_INI_DIR/php.ini-production" "$PHP_INI_DIR/php.ini"

RUN sed -i 's/$;extension=pgsql/extension=pgsql/' /usr/local/etc/php/php.ini

RUN sed -i 's/$;extension=intl/extension=intl/' /usr/local/etc/php/php.ini


# 1. Clone the github repository or Download ZIP
# Go to the https://github.com/dalibo/emaj_web URL and click on the "Clone or Download" button.
RUN wget https://github.com/dalibo/emaj_web/archive/refs/heads/master.zip

# If you download the ZIP file, extract the zip package.
RUN unzip ./master.zip

# 2- Configure Emaj_web

# Edit the conf/config.inc.php.
#  It mainly deals with the configuration of PostgreSQL servers connections.
# If you mess up the configuration file, you can recover it from the config.inc.php-dist file.

RUN cp emaj_web-master/conf/config.inc.php-dist emaj_web-master/conf/config.inc.php

ENV config_file=emaj_web-master/conf/config.inc.php

RUN sed -i "s/\['host'\] = '';/['host'] = '${db_host}';/" $config_file 

RUN sed -i "s/\['defaultdb'\] = 'template1';/['defaultdb'] = '${defaultdb}';/" $config_file

# If extra login security is true, then logins with no
# password or certain usernames (pgsql, postgres, root, administrator)
# will be denied. Only set this false once you have read the FAQ and
# understand how to change PostgreSQL's pg_hba.conf to enable
# passworded local connections.
RUN sed -i "s/\['extra_login_security'\] = true;/['extra_login_security'] = ${extra_login_security};/" $config_file

# Path of psql as seen in https://packages.debian.org/bullseye/all/postgresql-client-common/filelist
RUN sed -i "s|/\* Uncomment and adjust the value of both parameters \*/|\$conf['psql_path'] = '/usr/bin/psql';\n      \$conf['temp_dir'] = '/tmp'; |" $config_file

# RUN cat $config_file # May help debbugging

RUN cp -r emaj_web-master/* /var/www/html

```
