### ISSUE TITLE
Doubt on a path in create_clusert.sh script

### ISSUE THREAD

**Issue by tilkow** [dalibo/emaj#8]
Hello Philippe,
I have the impression that 'postgresql' is too much after the 'share' directory in the path.

https://github.com/beaud76/emaj/blob/44fa362a0b70d612a9671064229d1b5b9e935822/tools/create_cluster.sh#L73

**Comment by beaud76** [comment]
Hi tilkow,
On my server at least, this path is correct. But this may differ with some other installations.
I compile the sources by myself and execute the ./configure command with a --prefix=/usr/local/pgXXX.
This probably means that this path in the script has to be customized. 
Using the result of pg_config would not help for me with a lot of different pg versions installed on the server.
I keep a note on my side to improve this.
Thanks for having reported this issue.

**Comment by beaud76** [comment]
Issue processed with commit 27b020b6aa6c25f22ebf8b0cffc4628edb35c951
