### ISSUE TITLE
files to copy - Windows installation procedures (documentation)

### ISSUE THREAD

**Issue by mayeulk** [dalibo/emaj#9]
On Linux, one command for the installation is 
`cp sql/emaj* $(pg_config --sharedir)/extension/.`
or on some systems (Debian 9 - stretch with PostgreSQL 10):
`cp sql/emaj* /usr/share/postgresql/10/extension/.`

However, those commands  are NOT equivalent to what is said on the Windows documentation: "Copy the files emaj.control and sql/emaj–* into the share\extension folder of the PostgreSQL installation folder "
In effect, sql/emaj–* (with a dash) will not match files like sql/emaj_* (with underscore) but "cp sql/emaj* " will match those files (for instance: emaj_demo.sql )

I guess the Windows documentation in [https://github.com/beaud76/emaj/blob/master/docs/en/install.rst](https://github.com/beaud76/emaj/blob/master/docs/en/install.rst) should read:

"Copy the files emaj.control and sql/emaj* into the share\extension folder"
(without the dash)

**Comment by beaud76** [comment]
Hi mayeulk,
Good catch. There is indeed an inconsistency between both procedures. As you noticed, the difference deals with the emaj_demo.sql and also 3 other files. But all these 4 scripts are psql script and not directly linked to the extension management by postgres. So it is not necessary to copy them to the $SHAREDIR/extension directory. 
But the question is now "is it good to copy them to this directory ?"
For the moment, my feeling is that is would be better to NOT copy them $SHAREDIR/extension directory and keep them with other interesting files like both php clients or the documentation.
So I would be more inclined to adjust the Linux installation procedure.
Anyway, I will fix the documentation soon.
Thanks for having reported the issue.

**Comment by beaud76** [comment]
The change is integrated into the commit 7399fc5.
